[package]
name = "billdoor-desktop"
version = "1.0.0"
description = "BillDoor Desktop Application"
authors = ["Orbitex Team <engineering@orbitex.in>"]
license = "Proprietary"
repository = "https://github.com/Ayanmathur/BillDoor"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
