'use server';

/**
 * Billit — Catalog Server Actions (§5.4)
 *
 * CRUD for catalog_items (products/services).
 * Barcode auto-generation when client.barcode_enabled = true.
 * All RLS-scoped to authenticated client.
 */

import { createClient } from '@/lib/supabase/server';
import { z } from 'zod';

const catalogItemSchema = z.object({
  name: z.string().trim().min(1).max(200),
  type: z.enum(['product', 'service']),
  price: z.number().min(0).max(9999999),
  unit: z.string().max(20).optional(),
  gstPercent: z.number().min(0).max(100).optional(),
  description: z.string().max(500).optional(),
  barcodeValue: z.string().max(50).optional(),
  bufferAfterMin: z.number().min(0).max(1440).optional(),
});

// ============================================================
// Fetch catalog items
// ============================================================
export async function fetchCatalogAction(search?: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized.', items: null };

  let query = supabase
    .from('catalog_items')
    .select('*')
    .eq('client_id', user.id)
    .eq('active', true)
    .order('name');

  if (search) query = query.ilike('name', `%${search}%`);

  const { data, error } = await query;
  if (error) return { error: 'Failed to fetch catalog.', items: null };
  return { items: data };
}

// ============================================================
// Add catalog item
// ============================================================
export async function addCatalogItemAction(data: z.infer<typeof catalogItemSchema>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized.' };

  const parsed = catalogItemSchema.safeParse(data);
  if (!parsed.success) return { error: parsed.error.errors[0]?.message || 'Invalid input.' };

  // Check barcode setting
  const { data: client } = await supabase
    .from('clients')
    .select('barcode_enabled')
    .eq('id', user.id)
    .single();

  let barcodeValue = parsed.data.barcodeValue || null;
  let barcodeAutoGenerated = false;

  // Auto-generate barcode if enabled and not provided
  if (client?.barcode_enabled && !barcodeValue) {
    const namePrefix = parsed.data.name
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .slice(0, 8);

    // Get next sequence number for this client
    const { count } = await supabase
      .from('catalog_items')
      .select('id', { count: 'exact', head: true })
      .eq('client_id', user.id);

    const seqNum = String((count || 0) + 1).padStart(4, '0');
    barcodeValue = `${namePrefix}-${seqNum}`;
    barcodeAutoGenerated = true;
  }

  // Check barcode uniqueness
  if (barcodeValue) {
    const { data: existing } = await supabase
      .from('catalog_items')
      .select('id')
      .eq('client_id', user.id)
      .eq('barcode_value', barcodeValue)
      .eq('active', true)
      .single();
    if (existing) return { error: 'Barcode value already exists for another item.' };
  }

  const { error } = await supabase
    .from('catalog_items')
    .insert({
      client_id: user.id,
      name: parsed.data.name,
      type: parsed.data.type,
      price: parsed.data.price,
      unit: parsed.data.unit || null,
      gst_percent: parsed.data.gstPercent || 0,
      description: parsed.data.description || null,
      barcode_value: barcodeValue,
      barcode_auto_generated: barcodeAutoGenerated,
      buffer_after_min: parsed.data.bufferAfterMin || 0,
    });

  if (error) return { error: 'Failed to add item. Try again.' };
  return {};
}

// ============================================================
// Update catalog item
// ============================================================
export async function updateCatalogItemAction(id: string, data: z.infer<typeof catalogItemSchema>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized.' };

  const parsed = catalogItemSchema.safeParse(data);
  if (!parsed.success) return { error: parsed.error.errors[0]?.message || 'Invalid input.' };

  // Check barcode uniqueness (exclude self)
  if (parsed.data.barcodeValue) {
    const { data: existing } = await supabase
      .from('catalog_items')
      .select('id')
      .eq('client_id', user.id)
      .eq('barcode_value', parsed.data.barcodeValue)
      .neq('id', id)
      .eq('active', true)
      .single();
    if (existing) return { error: 'Barcode value already exists for another item.' };
  }

  const { error } = await supabase
    .from('catalog_items')
    .update({
      name: parsed.data.name,
      type: parsed.data.type,
      price: parsed.data.price,
      unit: parsed.data.unit || null,
      gst_percent: parsed.data.gstPercent || 0,
      description: parsed.data.description || null,
      barcode_value: parsed.data.barcodeValue || null,
      barcode_auto_generated: false, // Manual edit flips to false
      buffer_after_min: parsed.data.bufferAfterMin || 0,
    })
    .eq('id', id)
    .eq('client_id', user.id);

  if (error) return { error: 'Failed to update. Try again.' };
  return {};
}

// ============================================================
// Soft-delete catalog item
// ============================================================
export async function deleteCatalogItemAction(id: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Unauthorized.' };

  const { error } = await supabase
    .from('catalog_items')
    .update({ active: false })
    .eq('id', id)
    .eq('client_id', user.id);

  if (error) return { error: 'Failed to delete.' };
  return {};
}
